#Requires -Version 5.1
<#
.SYNOPSIS
    Ulak OS one-liner installer for Windows PowerShell.

.DESCRIPTION
    Clones (or pulls) the Ulak OS repo into $env:USERPROFILE\.ulak-os and puts
    a ulak.cmd wrapper on a directory in $env:PATH so `ulak` works from any
    shell. Idempotent.

.PARAMETER DryRun
    Prints every action without touching the filesystem or network.

.PARAMETER UlakHome
    Override the install location. Default: $env:USERPROFILE\.ulak-os

.PARAMETER RepoUrl
    Override the git URL. Default: https://github.com/osrt91/ulak-os.git

.PARAMETER Branch
    Branch to track. Default: main

.EXAMPLE
    iwr -useb https://raw.githubusercontent.com/osrt91/ulak-os/main/scripts/install.ps1 | iex

.EXAMPLE
    .\install.ps1 -DryRun

.NOTES
    If your ExecutionPolicy is Restricted, run:
        Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
#>
[CmdletBinding()]
param(
    [switch]$DryRun,
    [string]$UlakHome = (Join-Path $env:USERPROFILE '.ulak-os'),
    [string]$RepoUrl  = 'https://github.com/osrt91/ulak-os.git',
    [string]$Branch   = 'main'
)

$ErrorActionPreference = 'Stop'

function Write-Ulak {
    param([string]$Message, [string]$Level = 'INFO')
    $tag = if ($DryRun) { '[ulak][dry-run]' } else { '[ulak]' }
    if ($Level -eq 'ERROR') {
        Write-Host "$tag ERROR: $Message" -ForegroundColor Red
    } elseif ($Level -eq 'HINT') {
        Write-Host "$tag Hint: $Message" -ForegroundColor Yellow
    } else {
        Write-Host "$tag $Message"
    }
}

function Invoke-Step {
    param([scriptblock]$Action, [string]$Description)
    if ($DryRun) {
        Write-Ulak "would: $Description"
    } else {
        & $Action
    }
}

# ---------- ExecutionPolicy advisory ----------
try {
    $policy = Get-ExecutionPolicy -Scope CurrentUser
    if ($policy -eq 'Restricted') {
        Write-Ulak "CurrentUser ExecutionPolicy is Restricted." 'HINT'
        Write-Ulak "Run: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned" 'HINT'
    }
} catch {
    # Non-fatal — keep going.
}

# ---------- Prerequisites ----------
Write-Ulak "checking prerequisites"

$git = Get-Command git -ErrorAction SilentlyContinue
if (-not $git) {
    Write-Ulak "git is required but not found on PATH" 'ERROR'
    Write-Ulak "install Git for Windows: https://git-scm.com/download/win" 'HINT'
    exit 1
}

# ---------- Clone or update ----------
$dotGit = Join-Path $UlakHome '.git'

if (Test-Path $dotGit) {
    Write-Ulak "existing install detected at $UlakHome - pulling latest"
    try {
        Invoke-Step { & git -C $UlakHome fetch --tags --prune origin | Out-Host } "git fetch"
        Invoke-Step { & git -C $UlakHome checkout $Branch             | Out-Host } "git checkout $Branch"
        Invoke-Step { & git -C $UlakHome pull --ff-only origin $Branch | Out-Host } "git pull --ff-only"
    } catch {
        Write-Ulak "git update failed: $_" 'ERROR'
        exit 1
    }
} elseif (Test-Path $UlakHome) {
    Write-Ulak "$UlakHome exists but is not a git checkout" 'ERROR'
    Write-Ulak "move it aside or pass -UlakHome <fresh-path>" 'HINT'
    exit 1
} else {
    Write-Ulak "cloning $RepoUrl into $UlakHome"
    try {
        Invoke-Step {
            & git clone --branch $Branch --depth 50 $RepoUrl $UlakHome | Out-Host
        } "git clone $RepoUrl"
    } catch {
        Write-Ulak "git clone failed: $_" 'ERROR'
        if (-not $DryRun -and (Test-Path $UlakHome)) {
            Write-Ulak "rolling back partial clone"
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $UlakHome
        }
        exit 1
    }
}

# ---------- Pick a bin directory on PATH ----------
function Select-BinDir {
    $preferred = @(
        (Join-Path $env:USERPROFILE 'bin'),
        (Join-Path $env:USERPROFILE '.local\bin'),
        (Join-Path $env:LOCALAPPDATA 'Ulak\bin')
    )
    foreach ($p in $preferred) {
        if ($env:PATH -split ';' -contains $p) { return $p }
    }
    # Default to the first preferred path; the user may need to add it to PATH.
    return $preferred[0]
}

$binDir = Select-BinDir
Write-Ulak "target bin directory: $binDir"

if (-not (Test-Path $binDir)) {
    Invoke-Step { New-Item -ItemType Directory -Path $binDir -Force | Out-Null } "mkdir $binDir"
}

# ---------- Write ulak.cmd wrapper ----------
$wrapperPath = Join-Path $binDir 'ulak.cmd'
$wrapperBody = @"
@echo off
REM Ulak OS CLI wrapper (PowerShell-backed).
REM Generated by scripts\install.ps1 — edits here will be overwritten.
setlocal
set "ULAK_HOME=$UlakHome"
powershell -NoProfile -ExecutionPolicy Bypass -File "%ULAK_HOME%\bin\ulak.ps1" %*
endlocal
"@

Invoke-Step {
    Set-Content -Path $wrapperPath -Value $wrapperBody -Encoding ASCII -Force
} "write $wrapperPath"

# ---------- Write the companion ulak.ps1 if the repo didn't ship one ----------
$ulakPs1 = Join-Path $UlakHome 'bin\ulak.ps1'
if (-not (Test-Path $ulakPs1)) {
    $ulakPs1Body = @'
#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
$ErrorActionPreference = 'Stop'
$UlakHome = $env:ULAK_HOME
if (-not $UlakHome) { $UlakHome = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path) }

function Read-UlakVersion {
    $p = Join-Path $UlakHome 'prompts\pack.json'
    if (Test-Path $p) {
        $j = Get-Content $p -Raw | ConvertFrom-Json
        return $j.version
    }
    return 'unknown'
}

function Invoke-UlakInit {
    param([string]$Target)
    if (-not $Target) { Write-Error "ulak init: missing <project-dir>"; exit 2 }
    if (-not (Test-Path $Target -PathType Container)) { Write-Error "not a directory: $Target"; exit 1 }
    $claude = Join-Path $Target 'CLAUDE.md'
    $import = "@$UlakHome\prompts\core\ulak-os-core-contract-2.0.0.md"
    if (Test-Path $claude) {
        if (Select-String -Path $claude -Pattern 'ulak-os-core-contract' -Quiet) {
            Write-Host "[ulak] CLAUDE.md already references Ulak OS core — no change."
            return
        }
        Copy-Item $claude "$claude.ulak-backup" -Force
        Add-Content $claude "`n# Ulak OS governance (added by ulak init)`n$import"
        Write-Host "[ulak] appended import to existing CLAUDE.md (backup: CLAUDE.md.ulak-backup)"
    } else {
        $header = "# $(Split-Path -Leaf $Target) — project memory`n`n$import`n`n## Runtime defaults`n- validation olmadan done deme`n- artefakt zincirini erken baslat`n"
        Set-Content -Path $claude -Value $header -Encoding UTF8
        Write-Host "[ulak] created CLAUDE.md with Ulak OS core import"
    }
    New-Item -ItemType Directory -Force -Path (Join-Path $Target 'reports\current') | Out-Null
}

$sub = if ($Args.Count -gt 0) { $Args[0] } else { 'help' }
$rest = if ($Args.Count -gt 1) { $Args[1..($Args.Count-1)] } else { @() }

switch ($sub) {
    '--version' { Write-Host "ulak $(Read-UlakVersion) (install: $UlakHome)" }
    '-v'        { Write-Host "ulak $(Read-UlakVersion) (install: $UlakHome)" }
    'version'   { Write-Host "ulak $(Read-UlakVersion) (install: $UlakHome)" }
    'init'      { Invoke-UlakInit -Target $rest[0] }
    'where'     { Write-Host $UlakHome }
    'update'    { & git -C $UlakHome pull --ff-only }
    'doctor'    {
        foreach ($s in 'scripts\validate-imports.sh','scripts\validate-schemas.sh','scripts\validate-vendor-parity.sh') {
            $full = Join-Path $UlakHome $s
            if (Test-Path $full) {
                Write-Host "[ulak] running $s"
                & bash $full
            }
        }
    }
    default {
        Write-Host "ulak — Ulak OS CLI wrapper`nUsage: ulak [--version|init <dir>|doctor|update|where|help]"
    }
}
'@
    Invoke-Step { Set-Content -Path $ulakPs1 -Value $ulakPs1Body -Encoding UTF8 -Force } "write $ulakPs1"
}

# ---------- PATH advisory ----------
if (-not (($env:PATH -split ';') -contains $binDir)) {
    Write-Ulak "NOTE: $binDir is not on your PATH for this session." 'HINT'
    Write-Ulak "Add it permanently (CurrentUser):" 'HINT'
    Write-Ulak "  [Environment]::SetEnvironmentVariable('PATH', `"$binDir;`" + [Environment]::GetEnvironmentVariable('PATH','User'), 'User')" 'HINT'
}

# ---------- Adapter detection ----------
Write-Ulak "detecting installed AI coding CLIs"
foreach ($cli in 'claude','codex','gemini') {
    $found = Get-Command $cli -ErrorAction SilentlyContinue
    if ($found) {
        Write-Ulak "  found: $cli ($($found.Source))"
    } else {
        Write-Ulak "  not found: $cli"
    }
}

Write-Host ""
Write-Host "[ulak] Installed. Next steps:"
Write-Host ""
Write-Host "  1. Verify:         ulak --version"
Write-Host "  2. Seed a project: cd C:\path\to\your-project; ulak init ."
Write-Host "  3. Open CLI:       claude   (or codex / gemini)"
Write-Host "  4. Full audit:     /director komple"
Write-Host ""
Write-Host "Docs: https://github.com/osrt91/ulak-os"
